# Basic linear algebra in Julia
Author: Andreas Noack Jensen (MIT) (http://www.econ.ku.dk/phdstudent/noack/)
(with edits from Jane Herriman)

First let's define a random matrix

In [1]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 1  3  1
 3  3  4
 1  2  3

Define a vector of ones

In [2]:
x = fill(1.0, (3,)) # = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Notice that $A$ has type Array{Int64,2} but $x$ has type Array{Float64,1}. Julia defines the aliases Vector{Type}=Array{Type,1} and Matrix{Type}=Array{Type,2}. 

Many of the basic operations are the same as in other languages
#### Multiplication

In [3]:
b = A*x

3-element Vector{Float64}:
  5.0
 10.0
  6.0

#### Transposition
As in other languages `A'` is the conjugate transpose, or adjoint

In [4]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3  1
 3  3  2
 1  4  3

and we can get the transpose with

In [5]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  3  1
 3  3  2
 1  4  3

#### Transposed multiplication
Julia allows us to write this without *

In [6]:
A'A

3×3 Matrix{Int64}:
 11  14  16
 14  22  21
 16  21  26

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [7]:
A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

`A\b` gives us the *least squares solution* if we have an overdetermined linear system (a "tall" matrix)

In [8]:
Atall = rand(3, 2)

3×2 Matrix{Float64}:
 0.527165   0.58089
 0.0970152  0.252751
 0.0536949  0.688065

In [9]:
Atall\b

2-element Vector{Float64}:
 -0.6667206888526852
 11.209478683599075

and the *minimum norm least squares solution* if we have a rank-deficient least squares problem

In [10]:
v = rand(3)
rankdef = hcat(v, v)

3×2 Matrix{Float64}:
 0.170066  0.170066
 0.235943  0.235943
 0.246205  0.246205

In [11]:
rankdef\b

2-element Vector{Float64}:
 16.138839280056004
 16.138839280056004

Julia also gives us the minimum norm solution when we have an underdetermined solution (a "short" matrix)

In [12]:
bshort = rand(2)
Ashort = rand(2, 3)

2×3 Matrix{Float64}:
 0.710763  0.681712   0.181071
 0.283298  0.0647305  0.993079

In [13]:
Ashort\bshort

3-element Vector{Float64}:
 0.3310062365426941
 0.2926134252091157
 0.1949453789617005

# The LinearAlgebra library

While much of linear algebra is available in Julia by default (as shown above), there's a standard library named `LinearAlgebra` that brings in many more relevant names and functions. In particular, it provides factorizations and some structured matrix types.  As with all packages, you can bring these additional features into your session with a `using LinearAlgebra`.

### Exercises

#### 10.1 
Take the inner product (or "dot" product) of a vector `v` with itself and assign it to variable `dot_v`.



In [14]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [17]:
using LinearAlgebra

dot_v = dot(v,v)

14

In [18]:
@assert dot_v == 14

#### 10.2 
Take the outer product of a vector v with itself and assign it to variable `outer_v`

In [29]:
outer_v = reshape(kron(v,v), (length(v), length(v)))
cross_v = cross(v,v)

3-element Vector{Int64}:
 0
 0
 0

In [25]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]

In [30]:
@assert cross_v == [0, 0, 0]

Please click on `Validate` on the top, once you are done with the exercises.